name: Kubernetes deployment
description: Deploy kubernetes manifests to the cloud
inputs:
  url:
    description: k8s url
    required: true
  secret:
    description: k8s secret
    required: true
  manifests:
    description: k8s manifests
    required: true
  images:
    description: k8s docker images
    required: true
outputs:
  message:
    description: Success message
    value: Deployment was successful
runs:
  using: composite
  steps:
    -
      name: Set the Kubernetes context
      uses: azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: ${{ inputs.url }}
        k8s-secret: ${{ inputs.secret }}
    -
      name: Checkout source code
      uses: actions/checkout@v3
    -
      name: Deploy to the Kubernetes cluster
      uses: azure/k8s-deploy@v1.3
      with:
        namespace: default
        manifests: ${{ inputs.manifests }}
        images: ${{ inputs.images }}
